apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-cm
  namespace: hello-app
data:
  name: "Russell"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ing
  namespace: hello-app
spec:
  rules:
    - host: hello-greetings.info
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hello-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: hello-app
spec:
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: ecoden/hello-app:latest
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: hello-cm
                  key: name